// Generated by https://quicktype.io

import type { PokeResult } from "./pokemon.interfaces";

export interface PokePage {
  data:        PokeResult[];
  start:       number;
  end:         number;
  size:        number;
  total:       number;
  currentPage: number;
  lastPage:    number;
  url:         URL;
}


export interface URL {
  current: string;
  next:    string;
  prev:    string;
}
